services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3000:3000'
      depends_on:
         - surrealdb
      environment:
         - PYTHONDONTWRITEBYTECODE=1
         - PYTHONUNBUFFERED=1
         - OPENAI_API_KEY=${OPENAI_API_KEY}
         - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
         - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
         - NEO4J_URI=${NEO4J_URI}
         - NEO4J_USERNAME=${NEO4J_USERNAME}
         - NEO4J_PASSWORD=${NEO4J_PASSWORD}
         - SURREALDB_URL=ws://surrealdb:8000/rpc
         - SURREALDB_EXTERNAL_URL=${SURREALDB_EXTERNAL_URL}
         - SURREALDB_USERNAME=${SURREALDB_USERNAME}
         - SURREALDB_PASSWORD=${SURREALDB_PASSWORD}

   surrealdb:
      image: surrealdb/surrealdb:latest
      user: root
      ports:
         - '8080:8000'
      labels:
         - traefik.enable=true
         - traefik.http.routers.surrealdb.rule=Host(`db.matchmaking.startmunich.de`)
         - traefik.http.services.surrealdb.loadbalancer.server.port=8000
      volumes:
         - surrealdb-data:/data
      environment:
         - SURREAL_USER=${SURREALDB_USERNAME}
         - SURREAL_PASS=${SURREALDB_PASSWORD}
      command: start --bind 0.0.0.0:8000 --user ${SURREALDB_USERNAME} --pass ${SURREALDB_PASSWORD} file:///data/database.db

volumes:
   surrealdb-data:
